// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDji7yieDakRMqgImqOks92mT_SM8p2V10',
    appId: '1:26283298263:web:c0144d4a5dbcf2618fcf92',
    messagingSenderId: '26283298263',
    projectId: 'controlflutter-4726c',
    authDomain: 'controlflutter-4726c.firebaseapp.com',
    storageBucket: 'controlflutter-4726c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq2V_4JRd7rRZIwycuw19GgHKfwU_7i68',
    appId: '1:26283298263:android:1369169b4792a8518fcf92',
    messagingSenderId: '26283298263',
    projectId: 'controlflutter-4726c',
    storageBucket: 'controlflutter-4726c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjLIX3ZuStL7eLWtcUE3KU_zmi6cZzV4I',
    appId: '1:26283298263:ios:467c1f81287d6f238fcf92',
    messagingSenderId: '26283298263',
    projectId: 'controlflutter-4726c',
    storageBucket: 'controlflutter-4726c.firebasestorage.app',
    iosBundleId: 'com.example.controlflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjLIX3ZuStL7eLWtcUE3KU_zmi6cZzV4I',
    appId: '1:26283298263:ios:467c1f81287d6f238fcf92',
    messagingSenderId: '26283298263',
    projectId: 'controlflutter-4726c',
    storageBucket: 'controlflutter-4726c.firebasestorage.app',
    iosBundleId: 'com.example.controlflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDji7yieDakRMqgImqOks92mT_SM8p2V10',
    appId: '1:26283298263:web:1df3ad061bd7682e8fcf92',
    messagingSenderId: '26283298263',
    projectId: 'controlflutter-4726c',
    authDomain: 'controlflutter-4726c.firebaseapp.com',
    storageBucket: 'controlflutter-4726c.firebasestorage.app',
  );
}
